backend/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('movie.urls', namespace='movie')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

backend/movie/urls.py
from django.urls import path

from . import views


app_name = 'movie'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),

    path('movies/', views.MovieList.as_view(), name='movie-list'),
    path('movies/top/', views.TopMovies.as_view(), name='top-movies'),
    path('movie/<int:pk>/', views.MovieDetail.as_view(), name='movie-detail'),
    path('movie/<int:movie_id>/vote/', views.CreateVote.as_view(), name='create-vote'),
    path('movie/<int:movie_id>/vote/<int:pk>/', views.UpdateVote.as_view(), name='update-vote'),
    path('movie/<int:movie_id>/image/upload/', views.MovieImageUpload.as_view(), name='movie-image-upload'),

    path('person/<int:pk>/', views.PersonDetail.as_view(), name='person-detail'),
]

backend/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

backend/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MyMDD{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'movie/css/main.css' %}">

    <style>
        .mymdb-masthead {
            background-color: #eeeeee;
            margin-bottom: 1em;
        }
    </style>
</head>

<body>

    <div class="mymdb-masthead">
        <div class="container">
            <nav class="nav">
                <div class="navbar-brand">MyMDB</div>
                <a href="{% url 'movie:movie-list' %}" class="nav-link">Movies</a>
                <a href="{% url 'movie:top-movies' %}" class="nav-link">Top 10 Movies</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'user:logout' %}" class="nav-link">Logout</a>
                {% else %}
                    <a href="{% url 'user:register' %}" class="nav-link">Registration</a>
                    <a href="{% url 'user:login' %}" class="nav-link">Login</a>
                {% endif %}
            </nav>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-8 mymdb-main">{% block main %}{% endblock %}</div>
            <div class="col-sm-3 offset-sm-1 mymdb-sidebar">{% block sidebar %}{% endblock %}</div>
        </div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>